# Generated by Django 4.2.7 on 2025-06-09 09:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Email address used for login and communications', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their email address', verbose_name='Đã xác thực'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional phone number for contact', max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief introduction about yourself (max 500 characters)', max_length=500, verbose_name='Giới thiệu bản thân'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chinese_level',
            field=models.CharField(choices=[('beginner', 'Người mới bắt đầu'), ('elementary', 'Sơ cấp'), ('intermediate', 'Trung cấp'), ('advanced', 'Nâng cao')], default='beginner', help_text='Current Chinese language proficiency level', max_length=20, verbose_name='Trình độ tiếng Trung hiện tại'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text='Current city of residence', max_length=100, verbose_name='Thành phố'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Vietnam', help_text='Country of residence', max_length=100, verbose_name='Quốc gia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Birth date for age-appropriate content and statistics', null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_study_time',
            field=models.CharField(blank=True, choices=[('morning', 'Buổi sáng (6:00 - 12:00)'), ('afternoon', 'Buổi chiều (12:00 - 18:00)'), ('evening', 'Buổi tối (18:00 - 22:00)'), ('night', 'Buổi đêm (22:00 - 6:00)')], help_text='Preferred time of day for studying', max_length=20, verbose_name='Thời gian học ưa thích'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_hours_per_week',
            field=models.IntegerField(default=0, help_text='Number of study hours per week (0-168)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)], verbose_name='Số giờ học/tuần'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_hsk_level',
            field=models.IntegerField(choices=[(1, 'HSK 1'), (2, 'HSK 2'), (3, 'HSK 3'), (4, 'HSK 4'), (5, 'HSK 5'), (6, 'HSK 6')], default=1, help_text='Target HSK level to achieve', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Mục tiêu HSK'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_customuser',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='accounts_profile',
        ),
    ]
