[tool.djlint]
profile = "django"
indent = 2
max_line_length = 120
preserve_leading_space = true
preserve_blank_lines = true
format_attribute_template_tags = true
format_css = true
format_js = true
ignore = "H006,H013,H020,H021,H023,H025,H030,H031"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2
