# Generated by Django 4.2.7 on 2025-06-10 08:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order'], 'verbose_name': 'Lựa chọn', 'verbose_name_plural': 'Lựa chọn'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['hsk_level', 'question_type', 'created_at'], 'verbose_name': 'Câu hỏi', 'verbose_name_plural': 'Câu hỏi'},
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={'verbose_name': 'Ngân hàng câu hỏi', 'verbose_name_plural': 'Ngân hàng câu hỏi'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(help_text='Nội dung lựa chọn', max_length=500, verbose_name='Lựa chọn'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Đáp án đúng'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=0, help_text='Thứ tự hiển thị (A=0, B=1, C=2, D=3)', verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question', verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, help_text='File âm thanh cho câu hỏi nghe', null=True, upload_to='questions/audio/', verbose_name='File âm thanh'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], default='medium', max_length=10, verbose_name='Độ khó'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Giải thích đáp án đúng', verbose_name='Giải thích'),
        ),
        migrations.AlterField(
            model_name='question',
            name='hsk_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.hsklevel', verbose_name='Cấp độ HSK'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='question',
            name='passage',
            field=models.TextField(blank=True, help_text='Đoạn văn đọc hiểu (nếu có)', verbose_name='Đoạn văn'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, help_text='Điểm số cho câu hỏi (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm số'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='Nội dung câu hỏi', verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questiontype', verbose_name='Loại câu hỏi'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='hsk_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.hsklevel', verbose_name='Cấp độ HSK'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên ngân hàng câu hỏi'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='question_banks', to='questions.question', verbose_name='Câu hỏi'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['hsk_level', 'question_type'], name='questions_q_hsk_lev_f0d0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'hsk_level'], name='questions_q_is_acti_c59981_idx'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_choice_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.UniqueConstraint(fields=('name', 'hsk_level'), name='unique_questionbank_name_per_level'),
        ),
    ]
