# Generated by Django 4.2.7 on 2025-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSKLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('vocabulary_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'HSK Level',
                'verbose_name_plural': 'HSK Levels',
                'ordering': ['level'],
            },
        ),
    ]
