# Generated by Django 4.2.7 on 2025-06-09 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(default=120)),
                ('total_questions', models.IntegerField(default=40)),
                ('passing_score', models.FloatField(default=60.0, help_text='Passing score percentage')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('randomize_questions', models.BooleanField(default=True)),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('allow_retake', models.BooleanField(default=True)),
                ('max_attempts', models.IntegerField(default=3)),
                ('hsk_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.hsklevel')),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionbank')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_remaining', models.IntegerField(blank=True, help_text='Minutes remaining', null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('earned_points', models.IntegerField(default=0)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('questions_order', models.JSONField(blank=True, default=list)),
                ('current_question_index', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Session',
                'verbose_name_plural': 'Exam Sessions',
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'user', 'created_at')},
            },
        ),
    ]
