# Generated by Django 4.2.7 on 2025-06-10 10:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_choice_options_alter_question_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kỳ thi', 'verbose_name_plural': 'Kỳ thi'},
        ),
        migrations.AlterModelOptions(
            name='examsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phiên thi', 'verbose_name_plural': 'Phiên thi'},
        ),
        migrations.AddField(
            model_name='examsession',
            name='user_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Câu trả lời của người dùng'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='allow_retake',
            field=models.BooleanField(default=True, verbose_name='Cho phép thi lại'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(default=120, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)], verbose_name='Thời gian thi (phút)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='hsk_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.hsklevel', verbose_name='Cấp độ HSK'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='max_attempts',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Số lần thi tối đa'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.FloatField(default=60.0, help_text='Điểm đậu (%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Điểm đậu'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionbank', verbose_name='Ngân hàng câu hỏi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=True, verbose_name='Xáo trộn câu hỏi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='show_results_immediately',
            field=models.BooleanField(default=True, verbose_name='Hiển thị kết quả ngay'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề kỳ thi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Tổng số câu hỏi'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành lúc'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='current_question_index',
            field=models.IntegerField(default=0, verbose_name='Chỉ số câu hỏi hiện tại'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='earned_points',
            field=models.IntegerField(default=0, verbose_name='Điểm đạt được'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Kỳ thi'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Đã đậu'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Phần trăm'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='questions_order',
            field=models.JSONField(blank=True, default=list, verbose_name='Thứ tự câu hỏi'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm số'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu lúc'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('not_started', 'Chưa bắt đầu'), ('in_progress', 'Đang thi'), ('completed', 'Đã hoàn thành'), ('expired', 'Đã hết hạn')], default='not_started', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='time_remaining',
            field=models.IntegerField(blank=True, help_text='Thời gian còn lại (phút)', null=True, verbose_name='Thời gian còn lại'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Tổng điểm'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Thí sinh'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['hsk_level', 'is_active'], name='exams_exam_hsk_lev_779343_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_date', 'end_date'], name='exams_exam_start_d_3b125a_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', 'status'], name='exams_exams_user_id_cfaeab_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam', 'status'], name='exams_exams_exam_id_84ab90_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['started_at'], name='exams_exams_started_567337_idx'),
        ),
    ]
