# Generated by Django 4.2.7 on 2025-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_options_alter_examsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, help_text='Hướng dẫn chi tiết cho thí sinh', verbose_name='Hướng dẫn thi'),
        ),
    ]
