# Generated by Django 4.2.7 on 2025-06-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_navigation',
            field=models.BooleanField(default=True, help_text='Cho phép thí sinh quay lại câu trước', verbose_name='Cho phép di chuyển giữa các câu'),
        ),
        migrations.AddField(
            model_name='exam',
            name='require_full_completion',
            field=models.BooleanField(default=False, help_text='Bắt buộc trả lời tất cả câu hỏi', verbose_name='Yêu cầu hoàn thành tất cả câu'),
        ),
    ]
