# Generated by Django 4.2.7 on 2025-06-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_allow_navigation_exam_require_full_completion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together=set(),
        ),
    ]
