# Generated by Django 4.2.7 on 2025-06-12 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_choice_options_alter_question_options_and_more'),
        ('exams', '0005_alter_examsession_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_answer', models.TextField(blank=True, help_text='For text-based questions', verbose_name='Câu trả lời dạng text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Đúng')),
                ('points_earned', models.FloatField(default=0.0, verbose_name='Điểm đạt được')),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Time spent on this question', verbose_name='Thời gian làm bài (giây)')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='exams.examsession', verbose_name='Phiên thi')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Câu hỏi')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.choice', verbose_name='Lựa chọn')),
            ],
            options={
                'verbose_name': 'Câu trả lời',
                'verbose_name_plural': 'Câu trả lời',
                'ordering': ['question__id'],
                'unique_together': {('exam_session', 'question')},
            },
        ),
    ]
